/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TCodeEditor: typeof import('./src/components/TCodeEditor.vue')['default']
    TEditor: typeof import('./src/components/TEditor.vue')['default']
    TMonacoEditor: typeof import('./src/components/TMonacoEditor.vue')['default']
    TNavBar: typeof import('./src/components/TNavBar.vue')['default']
  }
}
